/**
 * 3D World — Core Module (READ-ONLY, overwritten on deploy)
 * Do not edit this file. It provides the game loop and re-exports all template modules.
 *
 * Game code imports from this file:
 *   import { world, assets, physics, player, network, ui, THREE } from '../template/js/core.js';
 */
const TEMPLATE_VERSION = 75;

// Re-export all modules
import { scene, camera, renderer, clock, THREE, lighting } from './world.js';
import * as physics from './physics.js';
import * as assets from './assets.js';
import * as playerModule from './player.js';
import * as network from './network.js';
import * as ui from './ui.js';
import * as primitives from './primitives.js';
import * as constraints from './constraints.js';
import * as features from './features.js';

const world = { scene, camera, renderer, clock, lighting };

// Wire workspace.lighting reference
primitives.workspace.lighting = lighting;

// Expose spawn position function for player.js to use
window._gip3dwGetSpawnPosition = primitives.getSpawnPosition;

// Game hooks — set by game code
let gameInit = null;
let gameUpdate = null;
let gameConfig = null;
let statsTimer = 0;

/** Register game initialization function. Called after template is ready. */
function onInit(fn) { gameInit = fn; }

/** Register game update function. Called every frame with (dt). */
function onUpdate(fn) { gameUpdate = fn; }

/** Set game configuration */
function setConfig(config) {
  gameConfig = config;
  if (config.title) {
    document.title = config.title;
    ui.setLoadingTitle(config.title);
  }
}

// --- Boot sequence ---
async function boot() {
  try {
    // Log game version + build info
    const version = gameConfig?.version || '?';
    const title = gameConfig?.title || '3D World';
    const buildMeta = document.querySelector('meta[name="gip3dw-build"]');
    const build = buildMeta ? buildMeta.content : 'dev';
    console.log(`[3D World] ${title} v${version} | Template v${TEMPLATE_VERSION} | Build: ${build}`);

    ui.updateLoadingProgress(0.05, 'Initializing physics...');
    await physics.initPhysics();

    ui.updateLoadingProgress(0.15, 'Loading assets...');
    await assets.initAssets((p, msg) => ui.updateLoadingProgress(0.15 + p * 0.2, msg));

    // Preload assets from config
    if (gameConfig?.preload?.length) {
      await assets.preload(gameConfig.preload, (p, msg) => ui.updateLoadingProgress(0.35 + p * 0.3, msg));
    }

    ui.updateLoadingProgress(0.7, 'Connecting...');
    await network.initNetwork(
      gameConfig?.network || {},
      (p, msg) => ui.updateLoadingProgress(0.7 + p * 0.15, msg),
    );

    // Wire up position sync
    network.setSyncPositionFn(() => {
      const pos = playerModule.getPosition();
      return { x: pos.x, y: pos.y, z: pos.z, rotation: playerModule.playerMesh?.rotation.y || 0 };
    });

    ui.updateLoadingProgress(0.9, 'Starting game...');

    // Call game init
    if (gameInit) await gameInit();

    // Initialize opt-in features (after game init so game code can set up first)
    await features.initFeatures(gameConfig?.features, {
      world, scene, camera, renderer, physics, player: playerModule,
      network, ui, assets, primitives, constraints, THREE,
    });

    ui.updateLoadingProgress(1, 'Ready!');

    // Feed version info to debug panel
    ui.setDebugInfo({
      fwVersion: TEMPLATE_VERSION,
      appVersion: version,
      appTitle: title,
    });

    // Connect to platform event stream (auto-refresh on deploy, future events)
    connectPlatformEvents();

    // Start game loop
    setTimeout(() => {
      ui.hideLoading();
      requestAnimationFrame(loop);
    }, 300);

  } catch (err) {
    console.error('[Core] Boot failed:', err);
    ui.updateLoadingProgress(1, `Error: ${err.message}`);
  }
}

/** Connect to platform SSE for real-time events (deploy reload, future: config, notify, kill) */
function connectPlatformEvents() {
  const meta = document.querySelector('meta[name="gip3dw-app"]');
  if (!meta || !meta.content) return; // no app GUID = not deployed, skip

  const appGuid = meta.content;
  const apiBase = 'https://a.gipity.ai';

  try {
    const es = new EventSource(`${apiBase}/api/${appGuid}/events`);

    es.addEventListener('deploy', () => {
      console.log('[3D World] New version deployed, reloading...');
      const toast = document.createElement('div');
      toast.textContent = 'Updating\u2026';
      toast.style.cssText = 'position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:rgba(0,0,0,0.85);color:#f26522;padding:16px 32px;border-radius:8px;font:16px monospace;z-index:99999;pointer-events:none;';
      document.body.appendChild(toast);
      setTimeout(() => location.reload(), 800);
    });

    // Future: es.addEventListener('config', (e) => { ... });
    // Future: es.addEventListener('notify', (e) => { ... });
    // Future: es.addEventListener('kill', (e) => { ... });

    es.onerror = () => console.debug('[3D World] Event stream reconnecting...');
  } catch {
    // EventSource not supported or blocked — game works fine without it
  }
}

function loop() {
  requestAnimationFrame(loop);
  clock.update();
  const dt = Math.min(clock.getDelta(), 0.05); // Cap delta to avoid spiraling

  physics.step(dt);
  primitives.updateParts(dt); // sync physics → meshes, run snap detection
  playerModule.updatePlayer(dt);

  if (gameUpdate) gameUpdate(dt);
  features.updateFeatures(dt);

  ui.updateDebugFps(dt);
  // Update part count in debug panel (piggyback on FPS timer — once per second)
  ui.setDebugInfo({ partCount: primitives.workspace.parts.size });

  // Feed renderer/physics stats to debug panel (~4Hz)
  statsTimer += dt;
  if (statsTimer > 0.25) {
    statsTimer = 0;
    const info = renderer.info;
    let awake = 0;
    if (physics.world) {
      physics.world.forEachRigidBody((b) => { if (!b.isSleeping()) awake++; });
    }
    ui.setRendererInfo({
      drawCalls: info.render.calls,
      triangles: info.render.triangles,
      sceneObjects: scene.children.length,
      textures: info.memory.textures,
      geometries: info.memory.geometries,
      bodies: physics.world ? physics.world.bodies.len() : 0,
      awake,
    });
  }

  renderer.render(scene, camera);
}

// Wait for game code to register, then boot
// Game code should call setConfig() and onInit() synchronously on import,
// then core.js boots everything after a microtask
queueMicrotask(() => {
  // Give game.js time to register hooks
  setTimeout(boot, 0);
});

// Re-export workspace at top level for convenience
const { workspace } = primitives;

export {
  world,
  assets,
  physics,
  playerModule as player,
  network,
  ui,
  THREE,
  onInit,
  onUpdate,
  setConfig,
  // v13+ World Primitives
  primitives,
  constraints,
  workspace,
  features,
  TEMPLATE_VERSION,
};
