/**
 * 3D World — Network Module (READ-ONLY, overwritten on deploy)
 * Do not edit this file. It handles Colyseus multiplayer connection and player sync.
 *
 * Exports: initNetwork(), sendMessage, onMessage, getPlayers, room, isConnected
 */

let room = null;
let client = null;
let connected = false;
const remotePlayers = new Map(); // sessionId → { position, rotation, customData, mesh }
const messageHandlers = new Map(); // type → [callback]
const SYNC_RATE_MS = 50; // 20 Hz

/** Initialize network. Connects to Colyseus room for this game. */
async function initNetwork(config = {}, onProgress) {
  const roomName = config.room || 'game-lobby';
  const apiBase = config.apiBase || 'https://a.gipity.ai';
  const wsUrl = config.wsUrl || 'wss://rt.gipity.ai';

  try {
    // Get app token
    const appGuid = config.appGuid || getAppGuid();
    if (!appGuid) {
      console.debug('[Network] No app GUID — multiplayer disabled');
      if (onProgress) onProgress(1, 'Offline mode');
      return null;
    }

    if (onProgress) onProgress(0.3, 'Getting token...');

    const tokenRes = await fetch(`${apiBase}/api/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ app: appGuid }),
    });

    if (!tokenRes.ok) {
      console.warn('[Network] Token fetch failed:', tokenRes.status);
      if (onProgress) onProgress(1, 'Offline mode');
      return null;
    }

    const { data: { token } } = await tokenRes.json();
    if (onProgress) onProgress(0.6, 'Connecting...');

    // Load Colyseus client
    const { Client } = await import('https://esm.sh/colyseus.js@0.16.22?bundle-deps');
    client = new Client(wsUrl);

    room = await client.joinOrCreate('state', {
      app: appGuid,
      room: roomName,
      token,
    });

    connected = true;
    if (onProgress) onProgress(1, 'Connected');

    // Player join/leave
    if (room.state?.players) {
      room.state.players.onAdd((player, sessionId) => {
        if (sessionId === room.sessionId) return; // Skip self
        remotePlayers.set(sessionId, {
          position: { x: 0, y: 0, z: 0 },
          rotation: 0,
          customData: null,
          mesh: null,
        });
        emit('player_join', { sessionId, player });
      });

      room.state.players.onRemove((player, sessionId) => {
        const remote = remotePlayers.get(sessionId);
        if (remote) {
          emit('player_leave', { sessionId, mesh: remote.mesh });
          remotePlayers.delete(sessionId);
        }
      });
    }

    // Listen for position sync messages
    room.onMessage('pos', (data) => {
      const remote = remotePlayers.get(data.sid);
      if (remote) {
        remote.position = { x: data.x, y: data.y, z: data.z };
        remote.rotation = data.r || 0;
      }
    });

    // Generic message handler
    room.onMessage('*', (type, data) => {
      if (type === 'pos') return; // Already handled
      emit(type, data);
    });

    // Start sending position updates
    startSync();

    return room;
  } catch (err) {
    console.warn('[Network] Connection failed:', err.message);
    if (onProgress) onProgress(1, 'Offline mode');
    return null;
  }
}

/** Get the app GUID from the current URL path */
function getAppGuid() {
  // URL pattern: https://app.gipity.ai/{accountSlug}/{projectSlug}/
  // App GUID comes from metadata or a config value
  return window.__GIPITY_APP_GUID || null;
}

/** Send a custom message to all other players */
function sendMessage(type, data = {}) {
  if (room && connected) {
    room.send(type, data);
  }
}

/** Register a handler for a message type */
function onMessage(type, callback) {
  if (!messageHandlers.has(type)) messageHandlers.set(type, []);
  messageHandlers.get(type).push(callback);
}

function emit(type, data) {
  const handlers = messageHandlers.get(type);
  if (handlers) handlers.forEach(cb => cb(data));
}

/** Get all remote players */
function getPlayers() {
  return remotePlayers;
}

/** Get current session ID */
function getSessionId() {
  return room?.sessionId || null;
}

/** Position sync loop */
let syncGetPosition = null;

function setSyncPositionFn(fn) {
  syncGetPosition = fn;
}

function startSync() {
  setInterval(() => {
    if (!room || !connected || !syncGetPosition) return;
    const pos = syncGetPosition();
    room.send('pos', {
      sid: room.sessionId,
      x: pos.x,
      y: pos.y,
      z: pos.z,
      r: pos.rotation || 0,
    });
  }, SYNC_RATE_MS);
}

export {
  initNetwork,
  sendMessage,
  onMessage,
  getPlayers,
  getSessionId,
  setSyncPositionFn,
  room,
  connected as isConnected,
};
